#KNN CLASSIFICATION
###using IRIS dataset
###DONE BY: SHIRLYN JENITA J

In [39]:
import pandas as pd

In [40]:
import numpy as np 

In [41]:
import matplotlib.pyplot as plt

In [42]:
import seaborn as sns

In [43]:
iris = pd.read_csv("https://github.com/YBI-Foundation/Dataset/raw/main/IRIS.csv")

In [44]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [45]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [46]:
X = iris.drop(['species'], axis = 1)

In [47]:
y = iris['species']

In [48]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [49]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7, random_state = 2529)

In [52]:
X_train.shape , X_test.shape, y_train.shape, y_test.shape

((105, 4), (45, 4), (105,), (45,))

In [53]:
X_train

sepal_length  sepal_width  petal_length  petal_width
84            5.4          3.0           4.5          1.5
13            4.3          3.0           1.1          0.1
64            5.6          2.9           3.6          1.3
39            5.1          3.4           1.5          0.2
79            5.7          2.6           3.5          1.0
..            ...          ...           ...          ...
72            6.3          2.5           4.9          1.5
143           6.8          3.2           5.9          2.3
60            5.0          2.0           3.5          1.0
50            7.0          3.2           4.7          1.4
96            5.7          2.9           4.2          1.3

[105 rows x 4 columns]

In [54]:
from sklearn.preprocessing import StandardScaler

In [55]:
from sklearn.preprocessing import MinMaxScaler

In [56]:
ss = StandardScaler()

In [57]:
X_train = ss.fit_transform(X_train)

In [58]:
X_train

array([[-0.45274402, -0.05379268,  0.53306676,  0.5028967 ],
       [-1.88933563, -0.05379268, -1.49576942, -1.42728124],
       [-0.19154555, -0.27972194, -0.00397811,  0.227157  ],
       [-0.84454173,  0.84992435, -1.25708281, -1.28941139],
       [-0.06094631, -0.95750971, -0.06364976, -0.18645256],
       [-0.7139425 ,  2.43142916, -1.25708281, -1.42728124],
       [-0.84454173,  1.75364139, -1.0183962 , -1.01367168],
       [-0.19154555, -1.18343897,  0.17503685, -0.04858271],
       [-1.23633945,  0.84992435, -1.0183962 , -1.28941139],
       [ 0.72264911, -1.18343897,  0.83142502,  1.05437611],
       [-0.06094631, -0.05379268,  0.3540518 ,  0.08928714],
       [ 0.20025216,  0.39806584,  0.71208172,  0.91650626],
       [-0.84454173,  1.75364139, -1.25708281, -1.15154153],
       [-1.10574021, -1.40936823, -0.18299307, -0.18645256],
       [ 0.59204988, -0.27972194,  0.41372346,  0.227157  ],
       [ 0.85324835,  0.39806584,  1.01043998,  1.60585552],
       [-0.32214479,  2.

In [59]:
X_test = ss.fit_transform(X_test)

In [60]:
from sklearn.neighbors import KNeighborsClassifier

In [61]:
knncla = KNeighborsClassifier()

In [62]:
knncla.fit(X_train, y_train)

KNeighborsClassifier()

In [63]:
y_pred = knncla.predict(X_test)

In [64]:
from sklearn.metrics import classification_report , confusion_matrix

In [65]:
confusion_matrix(y_test , y_pred)

array([[14,  0,  0],
       [ 0,  9,  0],
       [ 0,  8, 14]])

In [66]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.53      1.00      0.69         9
           2       1.00      0.64      0.78        22

    accuracy                           0.82        45
   macro avg       0.84      0.88      0.82        45
weighted avg       0.91      0.82      0.83        45

